#mysql_web_host=5.158.149.121
# mysql_web_host=localhost
mysql_station_host=192.168.1.1
#dfr_db_host=5.158.149.121
dfr_db_host=192.168.1.1
mysql_user=dfr
mysql_password=usi
db=m9000
mysql_station_connection_url=jdbc:mysql://192.168.1.1:3306/m9000?validationQuery=Select 1"
#mysql_web_connection_url=jdbc:mysql://5.158.149.121:3306/m9000?autoReconnect=true&amp;validationQuery="Select 1"&amp;testOnBorrow=true"
mysql_web_connection_url=jdbc:mysql://localhost:3306/m9000?autoReconnect=true&amp;validationQuery=Select 1"
# uncomment for 12.04
# local_mysql_connection_url=jdbc:mysql://localhost:3306/m9000?autoReconnect=true&amp;validationQuery=Select 1"
# uncomment for 20.04
local_mysql_connection_url=jdbc:mysql://localhost:3306/m9000?autoReconnect=true&useSSL=false&validationQuery=Select 1"
mysql_driver=com.mysql.cj.jdbc.Driver
mysql_conn_attr=compress=false;auto-reconnect=true

# activemq In case of 64Kb network increase the following values to hours
time-to-live=300000
# wait time for transfer of files from station master to remote web master
files-transfer-wait-time=300000

# normal message queue response wait time. Other than file transfer every other commands including scope,monitor,config
mq-response-wait-time=30000
