#
# Log4J Settings for log4j 1.2.x (via jakarta-commons-logging)
#
# The five logging levels used by Log are (in order):
#
#   1. DEBUG (the least serious)
#   2. INFO
#   3. WARN
#   4. ERROR
#   5. FATAL (the most serious)


# Set root logger level to WARN and append to stdout
log4j.rootLogger=WARN, stdout,  stationLog, stationError

log4j.logger.com.usi.m9000=INFO
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout

log4j.logger.com.usi.m9000.station=INFO, stationLog, stationError
log4j.logger.com.usi.m9000.config=INFO, stationLog, stationError
log4j.additivity.com.usi.m9000.station=false

log4j.logger.com.usi.m9000.Master.M9kCreateComtradeFilesFromDB=INFO, masterComtradeLog, masterComtradeError
log4j.additivity.com.usi.m9000.Master.M9kCreateComtradeFilesFromDB=false


# Pattern to output the caller's file name and line number.
log4j.appender.stdout.layout.ConversionPattern=%d %5p (%c:%L) - %m%n

log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=M9kMaster.log

log4j.appender.R.MaxFileSize=10MB
# Keep one backup file
log4j.appender.R.MaxBackupIndex=1000

log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d %5p (%c:%L) - %m%n


log4j.appender.stationLog=org.apache.log4j.RollingFileAppender
log4j.appender.stationLog.File=/home/dfr/m9k/M9kComtradeUtil/Station-Info.log
log4j.appender.stationLog.Threshold=INFO
#log4j.appender.stationLog.filter=org.apache.log4j.varia.LevelMatchFilter
#log4j.appender.stationLog.filter.LevelToMatch=INFO
#log4j.appender.stationLog.filter.AcceptOnMatch=true

log4j.appender.stationLog.MaxFileSize=10MB
# Keep one backup file
log4j.appender.stationLog.MaxBackupIndex=1000

log4j.appender.stationLog.layout=org.apache.log4j.PatternLayout
log4j.appender.stationLog.layout.ConversionPattern=%d %5p (%c:%L) - %m%n

log4j.appender.stationError=org.apache.log4j.RollingFileAppender
log4j.appender.stationError.File=/home/dfr/m9k/M9kComtradeUtil/Station-Errors.log

log4j.appender.stationError.MaxFileSize=10MB
# Keep one backup file
log4j.appender.stationError.MaxBackupIndex=1000

log4j.appender.stationError.layout=org.apache.log4j.PatternLayout
log4j.appender.stationError.layout.ConversionPattern=%d %5p (%c:%L) - %m%n
log4j.appender.stationError.threshold=WARN

log4j.appender.masterComtradeLog=org.apache.log4j.RollingFileAppender
log4j.appender.masterComtradeLog.File=/home/dfr/m9k/M9kComtradeUtil/Master-Comtrade-Create-Info.log

log4j.appender.masterComtradeLog.MaxFileSize=10MB
# Keep one backup file
log4j.appender.masterComtradeLog.MaxBackupIndex=1000

log4j.appender.masterComtradeLog.layout=org.apache.log4j.PatternLayout
log4j.appender.masterComtradeLog.layout.ConversionPattern=%d %5p (%c:%L) - %m%n

log4j.appender.masterComtradeError=org.apache.log4j.RollingFileAppender
log4j.appender.masterComtradeError.File=/home/dfr/m9k/M9kComtradeUtil/MasterComtrade_create-Errors.log

log4j.appender.masterComtradeError.MaxFileSize=10MB
# Keep one backup file
log4j.appender.masterComtradeError.MaxBackupIndex=1000

log4j.appender.masterComtradeError.layout=org.apache.log4j.PatternLayout
log4j.appender.masterComtradeError.layout.ConversionPattern=%d %5p (%c:%L) - %m%n
log4j.appender.masterComtradeError.threshold=ERROR
