#IRIG Input local or UTC
irig-timezone=local

# User preferred time zone. If irig input is local, this will always be local
user-preferred-timezone=local

# self test of event board enable for new board and disable for old one - Change the value for reports in m9k-master.properties
event-board-test=enable

# cont analog data time limit in seconds
cont-analog-time-limit = 120

# cont data time limit in seconds
cont-data-time-limit = 300

#ser Limit number of rows to view to view in the SER panel
ser-results-limit=10000

#Alarms log Limit number of rows to view in the alarms log panel
alarmslog-results-limit=10000


#Faults limit number of rows to view to view in the DFR data panel
faults-results-limit=5000