# Master properties file
# Notification, Email, LDAP functionalities can be configured here

# Future implementation. ldap - To use active directory authentication; database - to use database authentication 
# auth-mechnaism=ldap

# LDAP enable/disable
ldap=disable
ldap-domain=USI\,DC=local
ldap-server-url=ldap://10.10.0.10:389
ldap-default-search-base=DC=USI\,DC=local
ldap-admin-group=m9000AdminGroup
ldap-guest-group=m9000GuestGroup
user-domain=USI

# PMU Chassis details
pmu-id=1
pmu-tcp-port=4712
pmu-udp-port=4713
pmu-stream-type=tcp
pmu-phasor-mode=Rectangular
; 22-Sep-2020 - Commented. Uncomment for Ubuntu 12.04 - pdc port is set to default 9978
; command-server-port=9978
; 22-Sep-2020 - Commented. Uncomment for Ubuntu 18.04/20.04 or Moxa - pdc port is changed to different than internal power supply
command-server-port=9979

# Master health status polling enable/disable
# If Enabled, Web Master polls every station for its status  
master-health-status-poll=disable

# Master health status polling frequency in Seconds
# It runs every n seconds specified to monitor stations
master-health-status-polling-frequency=300

# Web Master Notification Listener enable/disable
# If Enabled, Web Master listens to activemq queue named "Master.NotificationQ"(configured in context.xml)
master-notification-listener=disable

# Station Email Address
email-ids=sramasamy@faultrecorder.com
email-notification=disable
# Email configuration to the mail server
mail-server-host=mail.faultrecorder.com
mail-server-smtp-port=587
from-email=alerts@faultrecorder.com
email-pwd=
# Usi#1Dfr
# Daily Status Report
daily-status-report-generation=disable

# daily report repeat interval in minutes. default 1440 minutes
daily-report-repeat-interval=1440

# specific time of the day
# Hour of the day to run (0 - 23) hour(s)
daily-report-run-at-hour=0
# minutes 0 - 59
daily-report-run-at-minute=0

# Title of the daily status report
daily-status-report-title=DME Daily Health Report

# Title of station specific
station-specific-status-report-title=DME Alarms Report

# Report file directory location
report-files-dir=/data/m9k/status-reports/

# self test of event board enable for new board and disable for old one. Change the values for applet in m9k-applet.properties file
event-board-test=enable

# Transferred from m9k-applet.properties
#IRIG Input local or UTC
irig-timezone=local

# User preferred time zone. If irig input is local, this will always be local
user-preferred-timezone=local

# ALREADY HERE: Commented. self test of event board enable for new board and disable for old one - Change the value for reports in m9k-master.properties
# event-board-test=enable

# cont analog data time limit in seconds
cont-analog-time-limit = 120

# cont data time limit in seconds
cont-data-time-limit = 600

#ser Limit number of dates to view in the SER panel
ser-dates-limit=30

#Alarms log Limit number of rows to view in the alarms log panel
alarmslog-results-limit=10000


#Faults limit number of rows to view to view in the DFR data panel
faults-results-limit=5000

#SER email implementation - V1.0.9.1
# START: 15-May-2020 - SER enable/disable
ser-email=disable
# END: 15-May-2020
# SER listener runs for every seconds mentioned below. Defaults to 60 seconds. 
ser-listener-run-frequency=600
# File type to email - PDF or CSV
ser-email-file-type=PDF
# SER Directory name to store the emailed data
ser-email-dir=/data/m9k/ser-updates/
# SER email attachment size
ser-email-attachement-size=2