; To create comtrades file for continuous data that can be stored on to a NAS or any other storage
export-cont-comtrade=disable
export-cont-analog-comtrade-size-in-minutes=1 ; 1 minute worth of COMTRADEs are created. Mention the size in minutes. If it is anything over 60 minutes will default to 60 minutes
export-cont-measurements-comtrade-size-in-minutes=1 ; 1 minute worth of COMTRADEs are created. Mention the size in minutes. If it is anything over 60 minutes will default to 60 minutes
export-cont-comtrade-dir=/data/m9k/auto-exports ; Destination directory where the files needs to be exported 
export-cont-comtrade-days-to-retain=210 ; Specify the number of days to retain before deleting the files 
