app-name=USI M9000
web-major-version=1
web-minor-version=2
web-build-version=1
station-major-version=1
station-minor-version=2
station-build-version=1
m9000-db-script-major-version=1
m9000-db-script-minor-version=2
m9000-db-script-build-version=1
m9kdebug-major-version=1
m9kdebug-minor-version=2
m9kdebug-build-version=1
m9kbackup-major-version=1
m9kbackup-minor-version=2
m9kbackup-build-version=1
comtradeutil-major-version=1
comtradeutil-minor-version=2
comtradeutil-build-version=1
java-version=11.0.*
apache-tomcat-version=9.0
activemq-version=5.15.*
mysql-version=5.8.*	
