;System properties Modified 3rd
[station]
; Local Master Set Up
; Uncomment(Remove ; at the beginning of each line) below and modify for Local Master set up. Do not forget to comment Remote Master Set up below 
master-type=local
master_host=localhost
; Expected values push/pull/disable 
fault-data-transfer=disable

; Expected values pull/disable
lt-fault-data-transfer=disable

; Expected values push/disable
ser-data-transfer=disable

; Expected values push/disable
alarm-data-transfer=disable

; Report table data push/disable
reports-data-transfer=disable

; Transfers the cont and contAnalog data viewed in the GUI
cont-data-transfer=disable
cont-analog-data-transfer=disable

; End of Local Master set up

; Remote Master Set up
; Uncomment(Remove ; at the start) below and modify for Remote Master set up
; master-type=remote
; if remote db user and password to connect
; master_db_user=
; master_db_pwd=
; local-root-pwd=
; master_host=USI-PC

; Expected values push/pull/disable 
; fault-data-transfer=push

; Expected values pull/disable
; lt-fault-data-transfer=pull

; Expected values push/disable
; ser-data-transfer=push

; Expected values push/disable
; alarm-data-transfer=push

; Report table data push/disable
; reports-data-transfer=push

; Transfers the cont and contAnalog data viewed in the GUI push/disable
;cont-data-transfer=push
;cont-analog-data-transfer=push

; End of Remote Master set up

; common to both local and remote 

led-polling=enable

; Below should be enabled if faults are not pushed
create-comtrade=enable 

health_check_frequency=10 
watch-dog=enable

;To enable or disable notifications
master-notification=disable

; To enable/disable trigger notification in particular.
trigger-notify=disable

; To enable/disable SER notification in particular.
ser-notify=disable

; Enable to perform create(Remote) or drop(local) required tables and triggers else disable 
perform-db-setup=disable

; power supply static ip address
; 22-Sep-2020 - Commented. Uncomment for Ubuntu 12.04 - default external power supply
; power-supply=192.168.1.100
; 22-Sep-2020 - Commented. Uncomment for Ubuntu 18.04/20.04 or Moxa - power supply is internal in localhost
 power-supply=localhost
; Port to communicate to all chassis
port=9978

; IRIG Input local or UTC
irig-timezone=local

; User preferred time zone. If irig input is local, this will always be local
user-preferred-timezone=local

; User preference for setting alarms on or off for false triggers (Option: enable/disable) - Added on 22-Nov-2017 
user-disable-alarms=disable

; START 15-Sept-2022 - Cont Data - MySQL events - Days to Retain
drop-cont-osc-event-time=1451
drop-cont-measurements-event-run-time=1452
create-cont-osc-event-run-time=0610
create-cont-measurements-event-run-time=0620
remove-old-ser-event-run-time=0430
no-of-years-to-retain-ser=5
remove-old-dfrlog-event-run-time=0410
no-of-years-to-retain-dfrlog=1

; End 15-Sept-2022 
; Pdc details
pdc-xml-file-name-with-path=/home/dfr/.m9kpdc.xml

; 17-Feb-2023 - Alarms map info
alarms-map-file-name-with-path=/home/dfr/.m9kalarmsmap

; End of [station]
[calibration]
cal-report-path=/data/m9k/calibration-report
; Verification parameters
; gain tolerance in percentage %
gainTolerance=0.25
; Offset tolerance in integer
ofsTolerance=40
[eventtest]
eventtest-report-path=/data/m9k/eventtest-report
[health]
v5-low=4.8
v5-high=5.2
v3_3-low = 3.2
v3_3-high = 3.4
v2_5-low=2.4
v2_5-high=2.6
v1_5-low=1.4
v1_5-high=1.6
v1_2-low=1.1
v1_2-high=1.3
v1_8-low=1.7
v1_8-high=1.9
temp-low=1
temp-high=70
temp-warn-limit=3
fanRPM-low=2000
fanRPM-high=5000
diskSafetyLimit=80
dfrTimeDiffLimit=30
; Start disk cleanup when usage percentage hits the below value. Default 95%
diskCleanupLimitPercentage=92
; Stops recording if it hits this value. Defaults it to 98%. keep it greater than diskCleanupLimitPercentage to allow the cleanup
stopRecordingAtDiskLimitPercentage=95
; During cleanup retain at least specified number of days of faults. Default 30 days. NERC standard 10 days
minDaysOfFaultsToRetain=30
; Pause/Resume DFR recording
pauseRecording=false
; Relay Mappings Moved to GUI
;[RelayInfo]
;ONLINE=Relay_1
;TRIGGER=Relay_2
;CLOCK_SYNC=Relay_3
;COMMUNICATION=Relay_4
;POWER=Relay_5
;DISK=Relay_6
;TEMPERATURE=Relay_7
;WETTING_VOLTAGE=Relay_5
[master-notify]
; Health alert notification queue name web master listening to
master-notify-queue=Master.NotificationQ
[TriggerLed]
duration=10
[network]
; All in ms
socket-read-time-out=30000
socket-connection-time-out=30000
calibrate-socket-read-time-out=180000

; It logs a warning if a socket read takes more than specified time in ms
socket-read-warning-time=5000

[cont-data-units]
RMS=V
Frequency=Hz
Phasor=Phasor
Harmonic=V