label.username= Username
label.password= Password
label.login= Login
error.login= Invalid Username/Password. Please try again.

label.remoteid= Station Id
label.remotename= Station Name
label.total.analog= Total Analog Channels
label.total.digital= Total Digital Channels
label.total.dfrs= Total No of Units configured
label.system.stationId= StationId
label.system.samplerate= Sample Rate(DFR/SER)
label.system.ltsamplerate= Sample Rate(DDR/Continuous Analog)
label.system.linefrequency= Line Frequency
# label.system.ipaddress= IP Address
label.system.exportRate=DDR/Continuous Measurement Export Rate
label.system.recordingdevid= Recording Device ID
label.system.recordingdevname= Recording Device Name
label.system.prefaulttime= DFR Prefault Time(ms)
label.system.postfaulttime= DFR Postfault Time(ms)
label.system.ltrprefaulttime= DDR Prefault Time(sec)
label.system.ltrpostfaulttime= DDR Postfault Time(sec)
label.system.chatterlimit= Chatter Limit for Triggers
label.system.chatterrate= Chatter Rate for Triggers
label.system.triggerlimit= DFR Trigger Limit(ms)
label.system.ps= Primary or Secondary
label.system.signalTooLowFactor= Min. Full Scale %
label.system.eventDebounce= Event Debounce Time (ms)
label.system.wettingVoltageMonitor= Monitor Wetting Voltage?
label.system.eventTestCapability= Event Test
label.system.ddrDeckTimeLimit= DDR Records Size Limit in Seconds  

label.create=Create
label.create.station=New
label.edit.station=Edit
label.view.station=View
label.cancel=Cancel
label.next=Next
label.back=Back

label.save=Save

label.lg.autocalculate= Auto Calculate Fault Location(Ohm)
label.lg.positiveresistance= Positive Resistance(Ohm)
label.lg.positivereactance= Positive Reactance(Ohm)
label.lg.zeroresistance= Zero Resistance(Ohm)
label.lg.zeroreactance= Zero Reactance(Ohm)
label.lg.linelength= Line Length(MI)

label.pmu.id=PMU id
label.pmu.pmuPort=PMU Port
label.pmu.pmuUdpPort=PMU UDP Port
label.pmu.pmuStreamType=PMU Stream Type
label.pmu.phasorMode=PMU Phasor Mode
label.pmu.dataRate=PMU Data Rate
label.pmu.pmuStatus=PMU Status
label.pmu.maxwait=PMU Max Wait (ms)

errors.invalid=${getText(fieldName)} is invalid.
errors.required=${getText(fieldName)} is required.
errors.stationIndex=Please select a remote id to edit
errors.scopstationindex=Please select a remote id to view scope
errors.number=${getText(fieldName)} must be a number.
errors.range=${getText(fieldName)} is not in the range ${min} and ${max}.
errors.ipaddress=${getText(fieldName)} is not a valid ipaddress

label.dfrs=Select a chassis
label.selected.dfr=Selected chassis

label.hierarchy.subzones=Select a zone
label.system.parentZoneId=Assign it to a zone

label.system.triggerDuration=Trigger Duration (In Seconds)

label.system.contOscDaysToRetain=No. Of Days To Retain Continuous Osc. Data 
label.system.contMeasurementsDaysToRetain=No. Of Days To Retain Continuous Measurements Data

label.system.contOscExportTimeLimit=Export Continuous Osc. Data Time Limit (in seconds)
label.system.contMeasurementsExportTimeLimit=Export Continuous Measurements Data Time Limit (In Seconds)
