#
# Log4J Settings for log4j 1.2.x (via jakarta-commons-logging)
#
# The five logging levels used by Log are (in order):
#
#   1. DEBUG (the least serious)
#   2. INFO
#   3. WARN
#   4. ERROR
#   5. FATAL (the most serious)


# Set root logger level to WARN and append to stdout
log4j.logger.com.usi.m9000=DEBUG, masterLog, masterError
log4j.additivity.com.usi.m9000.station=false

# Pattern to output the caller's file name and line number.
log4j.appender.masterLog=org.apache.log4j.RollingFileAppender
log4j.appender.masterLog.File=/data/m9k/log/webmaster/Master-Info.log
log4j.appender.masterLog.MaxFileSize=10MB
# Keep one backup file
log4j.appender.masterLog.MaxBackupIndex=1000
log4j.appender.masterLog.layout=org.apache.log4j.PatternLayout
log4j.appender.masterLog.layout.ConversionPattern=%d %5p (%c:%L) - %m%n
log4j.appender.masterLog.Threshold=DEBUG
log4j.appender.masterLog.filter.a=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.masterLog.filter.a.LevelToMatch=INFO
log4j.appender.masterLog.filter.a.AcceptOnMatch=true
log4j.appender.masterLog.filter.b=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.masterLog.filter.b.LevelToMatch=DEBUG
log4j.appender.masterLog.filter.b.AcceptOnMatch=true
log4j.appender.masterLog.filter.c=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.masterLog.filter.c.LevelToMatch=ERROR
log4j.appender.masterLog.filter.c.AcceptOnMatch=false

log4j.appender.masterError=org.apache.log4j.RollingFileAppender
log4j.appender.masterError.File=/data/m9k/log/webmaster/Master-Errors.log

log4j.appender.masterError.MaxFileSize=10MB
# Keep one backup file
log4j.appender.masterError.MaxBackupIndex=1000

log4j.appender.masterError.layout=org.apache.log4j.PatternLayout
log4j.appender.masterError.layout.ConversionPattern=%d %5p (%c:%L) - %m%n
log4j.appender.masterError.threshold=ERROR

# disable apache low level logging
log4j.category.com.opensymphony.xwork2=OFF
log4j.category.org.apache.struts2=OFF
log4j.category.freemarker.beans=OFF
log4j.category.freemarker.cache=OFF

# configure Syslog facility LOCAL1 appender
log4j.appender.SYSLOG=org.apache.log4j.nt.NTEventLogAppender
log4j.appender.SYSLOG.syslogHost=localhost
log4j.appender.SYSLOG.facility=USER
log4j.appender.SYSLOG.source=M9000
log4j.appender.SYSLOG.layout=org.apache.log4j.PatternLayout
log4j.appender.SYSLOG.layout.conversionPattern=%m%n
log4j.appender.SYSLOG.filter.a=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.SYSLOG.filter.a.LevelToMatch=INFO
log4j.appender.SYSLOG.filter.a.AcceptOnMatch=true
log4j.appender.SYSLOG.filter.b=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.SYSLOG.filter.b.LevelToMatch=WARN
log4j.appender.SYSLOG.filter.b.AcceptOnMatch=false
log4j.appender.SYSLOG.filter.c=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.SYSLOG.filter.c.LevelToMatch=ERROR
log4j.appender.SYSLOG.filter.c.AcceptOnMatch=true

