#
# Log4J Settings for log4j 1.2.x (via jakarta-commons-logging)
#
# The five logging levels used by Log are (in order):
#
#   1. DEBUG (the least serious)
#   2. INFO
#   3. WARN
#   4. ERROR
#   5. FATAL (the most serious)


# Set root logger level to WARN and append to stdout
log4j.logger.com.usi.m9000=DEBUG, stationLog, stationError

# Pattern to output the caller's file name and line number.
log4j.appender.stationLog=org.apache.log4j.RollingFileAppender
log4j.appender.stationLog.File=/data/m9k/log/M9kBackup/m9kBackup-Info.log
log4j.appender.stationLog.MaxFileSize=10MB
# Keep one backup file
log4j.appender.stationLog.MaxBackupIndex=500

log4j.appender.stationLog.layout=org.apache.log4j.PatternLayout
log4j.appender.stationLog.layout.ConversionPattern=%d %5p (%c:%L) - %m%n

log4j.appender.stationLog.Threshold=DEBUG
log4j.appender.stationLog.filter.a=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.stationLog.filter.a.LevelToMatch=INFO
log4j.appender.stationLog.filter.a.AcceptOnMatch=true
log4j.appender.stationLog.filter.b=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.stationLog.filter.b.LevelToMatch=DEBUG
log4j.appender.stationLog.filter.b.AcceptOnMatch=false
log4j.appender.stationLog.filter.c=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.stationLog.filter.c.LevelToMatch=ERROR
log4j.appender.stationLog.filter.c.AcceptOnMatch=false


log4j.appender.stationError=org.apache.log4j.RollingFileAppender
log4j.appender.stationError.File=/data/m9k/log/M9kBackup/m9kBackup-Errors.log

log4j.appender.stationError.MaxFileSize=10MB
# Keep one backup file
log4j.appender.stationError.MaxBackupIndex=500

log4j.appender.stationError.layout=org.apache.log4j.PatternLayout
log4j.appender.stationError.layout.ConversionPattern=%d %5p (%c:%L) - %m%n
log4j.appender.stationError.filter.b=org.apache.log4j.varia.LevelMatchFilter
log4j.appender.stationError.filter.b.LevelToMatch=ERROR
log4j.appender.stationError.filter.b.AcceptOnMatch=true
log4j.appender.stationError.threshold=ERROR

