company=USI
timeCode=-5t
type=ASCII
dataDir=/data/m9k/faults
# contDataDir=/data/m9k/continuous/

#In seconds
run-frequency=5

#Trigger Limit (To calculate Deck Time) in Seconds
trigger-limit=10

# 30-Apr-2024 : Implement decktime and trigger limit separately. It's not expected to be changed by the user
decktime-limit=10

# Long Term Trigger Limit  in Seconds
ltr-trigger-limit=300

# wait latency 
latency-delay=2

#trigger table read has to use this time lapse to read start and start times
trigger-time-lapse=5

#Thread pool to cross record and merge
thread-pool-size=100

#dataDir=//mifile/USI Files/R&D Projects/New DFR/Comtrade/M9kShare/
#contDataDir=//195.1.1.73/m9k/Data/Continuous/

# Cross Trigger for Station. Cross triggers station if Y, and doesn't if N  
cross-trigger-station=Y 

# Fault Data cross record request wait time Milli seconds
fault-cross-req-wait-time=45000

# Web Master Type Local or Remote
 master-type=local
#master-type=remote

#IRIG Input local or UTC
irig-timezone=UTC

# User preferred time zone. If irig input is local, this will always be local
user-preferred-timezone=local

# Specifuc customer requirements for COMTRADE cfg. Copy column 4 val to column 2
sourceColumn=0
destColumn=0

# EMAIL settings regarding email server, port number, email account etc are set in m9k-master files
# Email faults settings
# Email notification for faults
email-notify-faults=disable

# Email notification for faults (enable or disable) - NOT IMPLEMENTED YET
# IF enabled it'll email only the faults that has boolean logic as true. Default all faults are emailed 
email-fault-boolean-logic-filter=disable

# Email for faults with attachment (yes/no) Default fault files are attached in the email based on the size limit below.
email-faults-with-attachment=enable

# Size limit for email attachment in MB - Default 2MB
email-attachement-size=2

# Daily Limit for number of fault emails sent 
email-faults-daily-limit = 10

# M9000 Configuration File extension
m9000-config-file-extn=sql

# Disk cleanup 
# Number of old faults to delete
total-faults-to-delete=10 
