<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.usi.com" xmlns:ns1="http://www.usi.com">
    <xs:element name="SubStation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:Host"/>
                <xs:element ref="ns1:TriggerGroup"/>
                <xs:element ref="ns1:Pdc"/>
                <xs:element ref="ns1:StationProperties"/>
                <xs:element ref="ns1:DFRs"/>
                <xs:element ref="ns1:GlobalLineGroups"/>
                <xs:element ref="ns1:GroupTriggers"/>
                <xs:element ref="ns1:Pmus"/>
                <xs:element ref="ns1:Measurements"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Host" type="xs:NCName"/>
    <xs:element name="TriggerGroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:ServerPort"/>
                <xs:element maxOccurs="unbounded" ref="ns1:DFRIP"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ServerPort" type="xs:integer"/>
    <xs:element name="DFRIP" type="xs:NMTOKEN"/>
    <xs:element name="Pdc">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:System"/>
                <xs:element ref="ns1:Pmus"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="StationProperties">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:Alarms"/>
                <xs:element ref="ns1:TriggerDuration"/>
                <xs:element ref="ns1:Health"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Alarms">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:Alarm"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Alarm">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:AlarmName"/>
                <xs:element ref="ns1:Relay"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="AlarmName" type="xs:NCName"/>
    <xs:element name="Relay" type="xs:NCName"/>
    <xs:element name="TriggerDuration" type="xs:integer"/>
    <xs:element name="Health">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:Temperature"/>
                <xs:element ref="ns1:Disk"/>
                <xs:element ref="ns1:V5"/>
                <xs:element ref="ns1:V3_3"/>
                <xs:element ref="ns1:V2_5"/>
                <xs:element ref="ns1:V1_5"/>
                <xs:element ref="ns1:V1_2"/>
                <xs:element ref="ns1:V1_8"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Temperature">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Disk">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
                <xs:element ref="ns1:CleanupLimit"/>
                <xs:element ref="ns1:StopRecordingLimit"/>
                <xs:element ref="ns1:MinDaysOfFaultsToRetain"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CleanupLimit" type="xs:integer"/>
    <xs:element name="StopRecordingLimit" type="xs:integer"/>
    <xs:element name="MinDaysOfFaultsToRetain" type="xs:integer"/>
    <xs:element name="V5">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="V3_3">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="V2_5">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="V1_5">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="V1_2">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="V1_8">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:HighLimit"/>
                <xs:element ref="ns1:LowLimit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="DFRs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:DFR"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="DFR">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:DEVICE"/>
                <xs:element ref="ns1:IPAddress"/>
                <xs:element ref="ns1:System"/>
                <xs:element ref="ns1:DataPool"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="DEVICE" type="xs:string"/>
    <xs:element name="IPAddress" type="xs:NMTOKEN"/>
    <xs:element name="DataPool">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:Channels"/>
                <xs:element minOccurs="0" ref="ns1:LineGroups"/>
                <xs:element minOccurs="0" ref="ns1:Algorithms"/>
                <xs:element minOccurs="0" ref="ns1:Exports"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Channels">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:Events"/>
                <xs:element minOccurs="0" ref="ns1:Analogs"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Events">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:EventInput"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="EventInput">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Channel"/>
                <xs:element ref="ns1:_Phase"/>
                <xs:element ref="ns1:_EventName"/>
                <xs:element ref="ns1:_EnableDfr"/>
                <xs:element ref="ns1:_EnableSer"/>
                <xs:element ref="ns1:_NormalState"/>
                <xs:element minOccurs="0" ref="ns1:_TriggerModeDfr"/>
                <xs:element minOccurs="0" ref="ns1:_RecordMode"/>
                <xs:element minOccurs="0" ref="ns1:_MinValidEventSamples"/>
                <xs:element ref="ns1:_DebounceMs"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_EventName" type="xs:string"/>
    <xs:element name="_EnableDfr" type="xs:integer"/>
    <xs:element name="_EnableSer" type="xs:integer"/>
    <xs:element name="_NormalState" type="xs:NCName"/>
    <xs:element name="_TriggerModeDfr" type="xs:NCName"/>
    <xs:element name="_RecordMode" type="xs:NCName"/>
    <xs:element name="_MinValidEventSamples" type="xs:integer"/>
    <xs:element name="_DebounceMs" type="xs:decimal"/>
    <xs:element name="Analogs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:AnalogInput"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="AnalogInput">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_CircuitName"/>
                <xs:element ref="ns1:_Range"/>
                <xs:element ref="ns1:_Channel"/>
                <xs:element ref="ns1:_Phase"/>
                <xs:element ref="ns1:_InputType"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="ns1:_ExternalShunt"/>
                    <xs:element ref="ns1:_PhaseOffset"/>
                </xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="ns1:_Input"/>
                    <xs:element ref="ns1:_InputAdd"/>
                    <xs:element ref="ns1:_InputSub"/>
                    <xs:element ref="ns1:_TransformerPrimary"/>
                    <xs:element ref="ns1:_TransformerSecondary"/>
                    <xs:element ref="ns1:_Virtual"/>
                    <xs:element ref="ns1:_VirtualScale"/>
                </xs:choice>
                <xs:element ref="ns1:_Export"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="ns1:_Transducer"/>
                    <xs:element ref="ns1:_TransducerUnits"/>
                    <xs:element ref="ns1:_InP1"/>
                    <xs:element ref="ns1:_InP2"/>
                    <xs:element ref="ns1:_OutP1"/>
                    <xs:element ref="ns1:_OutP2"/>
                </xs:sequence>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_CircuitName" type="xs:string"/>
    <xs:element name="_Range" type="xs:integer"/>
    <xs:element name="_ExternalShunt" type="xs:decimal"/>
    <xs:element name="_PhaseOffset" type="xs:decimal"/>
    <xs:element name="_InputAdd" type="xs:string"/>
    <xs:element name="_InputSub" type="xs:string"/>
    <xs:element name="_TransformerPrimary" type="xs:integer"/>
    <xs:element name="_TransformerSecondary" type="xs:integer"/>
    <xs:element name="_Virtual" type="xs:integer"/>
    <xs:element name="_VirtualScale" type="xs:decimal"/>
    <xs:element name="_Export" type="xs:integer"/>
    <xs:element name="_Transducer" type="xs:integer"/>
    <xs:element name="_TransducerUnits" type="xs:NCName"/>
    <xs:element name="_InP1" type="xs:decimal"/>
    <xs:element name="_InP2" type="xs:decimal"/>
    <xs:element name="_OutP1" type="xs:integer"/>
    <xs:element name="_OutP2" type="xs:integer"/>
    <xs:element name="LineGroups">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:LineGroup"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="LineGroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Id"/>
                <xs:element ref="ns1:_LineGroupName"/>
                <xs:element ref="ns1:_AutoCalc"/>
                <xs:element ref="ns1:_PositiveResistance"/>
                <xs:element ref="ns1:_PositiveReactance"/>
                <xs:element ref="ns1:_ZeroResistance"/>
                <xs:element ref="ns1:_ZeroReactance"/>
                <xs:element ref="ns1:_LineMiles"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="ns1:_DecisionLogic"/>
                    <xs:element ref="ns1:_Comments"/>
                </xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:_Input"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_Comments" type="xs:string"/>
    <xs:element name="Algorithms">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:Monitor"/>
                <xs:element maxOccurs="unbounded" ref="ns1:And"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:Not"/>
                <xs:element maxOccurs="unbounded" ref="ns1:Average"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="ns1:Frequency"/>
                    <xs:element ref="ns1:Limits"/>
                    <xs:element ref="ns1:Magnitude"/>
                    <xs:element ref="ns1:NegativeSequence"/>
                    <xs:element ref="ns1:Output"/>
                    <xs:element ref="ns1:Phase"/>
                    <xs:element ref="ns1:PositiveSequence"/>
                    <xs:element ref="ns1:Power"/>
                    <xs:element ref="ns1:Rms"/>
                    <xs:element ref="ns1:Watts"/>
                    <xs:element ref="ns1:ZeroSequence"/>
                </xs:choice>
                <xs:element ref="ns1:Triggers"/>
                <xs:element minOccurs="0" ref="ns1:Pmus"/>
                <xs:element ref="ns1:VirtualMeasurement"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Monitor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Every"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_Every" type="xs:integer"/>
    <xs:element name="And">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element maxOccurs="unbounded" ref="ns1:_Input"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Not">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Average">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Frequency">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_Average"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Limits">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_HighLimit"/>
                <xs:element ref="ns1:_LowLimit"/>
                <xs:element ref="ns1:_RateOfChangeLimit"/>
                <xs:element ref="ns1:_RateOfChangeLimitPos"/>
                <xs:element ref="ns1:_RateOfChangeLimitNeg"/>
                <xs:element ref="ns1:_Duration"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_RateOfChangeLimit" type="xs:decimal"/>
    <xs:element name="_RateOfChangeLimitPos" type="xs:decimal"/>
    <xs:element name="_RateOfChangeLimitNeg" type="xs:decimal"/>
    <xs:element name="_Duration" type="xs:integer"/>
    <xs:element name="Magnitude">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_Harmonic"/>
                <xs:element minOccurs="0" ref="ns1:_Average"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_Harmonic" type="xs:integer"/>
    <xs:element name="NegativeSequence">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_InputType"/>
                <xs:element minOccurs="0" ref="ns1:_Average"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Output">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Channel"/>
                <xs:element ref="ns1:_Input"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Phase">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element minOccurs="0" ref="ns1:_Average"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="PositiveSequence">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element minOccurs="0" ref="ns1:_Average"/>
                <xs:element ref="ns1:_InputType"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Power">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_PowerType"/>
                <xs:element ref="ns1:_Inputs"/>
            </xs:sequence>
            <xs:attribute name="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_PowerType" type="xs:NCName"/>
    <xs:element name="_Inputs" type="xs:NCName"/>
    <xs:element name="Rms">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_Average"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Watts">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_Average"/>
                <xs:element ref="ns1:_InputType"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ZeroSequence">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Input"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="ns1:_Average"/>
                    <xs:element ref="ns1:_InputType"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Triggers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_TriggerOutHold"/>
                <xs:element maxOccurs="unbounded" ref="ns1:Trigger"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Trigger">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_TriggerName"/>
                <xs:element ref="ns1:_Enable"/>
                <xs:element minOccurs="0" ref="ns1:_Type"/>
                <xs:element ref="ns1:_ChanId"/>
                <xs:element ref="ns1:_Phase"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_ChatterLimit"/>
                <xs:element ref="ns1:_ChatterRate"/>
                <xs:element ref="ns1:_TriggerLimit"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_TriggerName" type="xs:NCName"/>
    <xs:element name="_ChanId" type="xs:integer"/>
    <xs:element name="VirtualMeasurement">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_Description"/>
                <xs:element ref="ns1:_Average"/>
                <xs:element ref="ns1:_Scale"/>
                <xs:element maxOccurs="unbounded" ref="ns1:VirtualMeasurementInput"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="VirtualMeasurementInput">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Scale"/>
                <xs:element ref="ns1:_Input"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Exports">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:Export"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Export">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_ExportName"/>
                <xs:element ref="ns1:_MeasurementType"/>
                <xs:element ref="ns1:_Enable"/>
                <xs:element ref="ns1:_Id"/>
                <xs:element ref="ns1:_Phase"/>
                <xs:element ref="ns1:_Units"/>
                <xs:element ref="ns1:_Input"/>
                <xs:element ref="ns1:_SampleRate"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_ExportName" type="xs:string"/>
    <xs:element name="_MeasurementType" type="xs:NCName"/>
    <xs:element name="_Units" type="xs:NCName"/>
    <xs:element name="_SampleRate" type="xs:integer"/>
    <xs:element name="GlobalLineGroups">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:GlobalLineGroup"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GlobalLineGroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Id"/>
                <xs:element ref="ns1:_LineGroupName"/>
                <xs:element ref="ns1:_AutoCalc"/>
                <xs:element ref="ns1:_PositiveResistance"/>
                <xs:element ref="ns1:_PositiveReactance"/>
                <xs:element ref="ns1:_ZeroResistance"/>
                <xs:element ref="ns1:_ZeroReactance"/>
                <xs:element ref="ns1:_LineMiles"/>
                <xs:element minOccurs="0" ref="ns1:_DecisionLogic"/>
                <xs:element ref="ns1:LgAnalogs"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="LgAnalogs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:_AnalogChannels"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_AnalogChannels">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_ChannelId"/>
                <xs:element ref="ns1:_RecId"/>
                <xs:element ref="ns1:_ExpId"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_ChannelId" type="xs:integer"/>
    <xs:element name="_RecId" type="xs:integer"/>
    <xs:element name="_ExpId" type="xs:integer"/>
    <xs:element name="GroupTriggers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_TriggerOutHold"/>
                <xs:element maxOccurs="unbounded" ref="ns1:GroupTrigger"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GroupTrigger">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Id"/>
                <xs:element ref="ns1:_Enable"/>
                <xs:element ref="ns1:_Type"/>
                <xs:element ref="ns1:_InputType"/>
                <xs:element ref="ns1:_LineGroupId"/>
                <xs:element ref="ns1:_LineGroupName"/>
                <xs:element ref="ns1:_ChatterLimit"/>
                <xs:element ref="ns1:_ChatterRate"/>
                <xs:element ref="ns1:_TriggerLimit"/>
                <xs:element minOccurs="0" ref="ns1:_HighLimit"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="ns1:_LowLimit"/>
                    <xs:element ref="ns1:_export"/>
                </xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_exportRate"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_LineGroupId" type="xs:integer"/>
    <xs:element name="_export" type="xs:integer"/>
    <xs:element name="_exportRate" type="xs:integer"/>
    <xs:element name="Measurements">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_TriggerOutHold"/>
                <xs:element maxOccurs="unbounded" ref="ns1:Measurement"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Measurement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:_Dfr"/>
                <xs:element ref="ns1:_Name"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:_Status"/>
                <xs:element minOccurs="0" ref="ns1:_ExportStatus"/>
                <xs:element ref="ns1:_PmuStatus"/>
                <xs:element minOccurs="0" ref="ns1:_DdrStatus"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_Name" type="xs:string"/>
    <xs:element name="_Status" type="xs:NCName"/>
    <xs:element name="_ExportStatus" type="xs:NCName"/>
    <xs:element name="_PmuStatus" type="xs:NCName"/>
    <xs:element name="_DdrStatus" type="xs:NCName"/>
    <xs:element name="System">
        <xs:complexType>
            <xs:sequence>
                <xs:sequence minOccurs="0">
                    <xs:element ref="ns1:_PdcStationName"/>
                    <xs:element ref="ns1:_StationId"/>
                    <xs:element ref="ns1:_ServerPort"/>
                    <xs:element ref="ns1:_CommandServerPort"/>
                    <xs:element ref="ns1:_NetworkProtocol"/>
                    <xs:element ref="ns1:_MaxWait"/>
                    <xs:element ref="ns1:_Verbose"/>
                    <xs:element ref="ns1:_DataRate"/>
                    <xs:element ref="ns1:_LineFreq"/>
                    <xs:element ref="ns1:_VerboseConcentrator"/>
                    <xs:element ref="ns1:UdpServers"/>
                </xs:sequence>
                <xs:sequence minOccurs="0">
                    <xs:element ref="ns1:DfrId"/>
                    <xs:element ref="ns1:RecordingDeviceId"/>
                    <xs:element ref="ns1:SampleRate"/>
                    <xs:element ref="ns1:LineFrequency"/>
                    <xs:element ref="ns1:ExportRate"/>
                    <xs:element ref="ns1:AnalogsCount"/>
                    <xs:element ref="ns1:DigitalsCount"/>
                    <xs:element ref="ns1:StationName"/>
                    <xs:element ref="ns1:PrefaultTime"/>
                    <xs:element ref="ns1:PostfaultTime"/>
                    <xs:element ref="ns1:LtrPrefaultTime"/>
                    <xs:element ref="ns1:LtrPostfaultTime"/>
                    <xs:element ref="ns1:DatabaseConnectString"/>
                    <xs:element ref="ns1:ChatterLimit"/>
                    <xs:element ref="ns1:ChatterRate"/>
                    <xs:element ref="ns1:TriggerLimit"/>
                    <xs:element ref="ns1:CrossRecordServerPort"/>
                    <xs:element ref="ns1:DatabaseDataType"/>
                    <xs:element ref="ns1:ExportAnalogBufferTime"/>
                    <xs:element ref="ns1:ExportAnalogSampleRate"/>
                    <xs:element ref="ns1:ExportBufferTime"/>
                    <xs:element ref="ns1:ContinuousOscillographyEnable"/>
                    <xs:element ref="ns1:AntiAliasFilterDelay"/>
                    <xs:element ref="ns1:DisableAllDatabaseUse"/>
                    <xs:element ref="ns1:InitSound"/>
                    <xs:element ref="ns1:Ps"/>
                    <xs:element ref="ns1:SignalTooLowFactor"/>
                </xs:sequence>
                <xs:sequence minOccurs="0">
                    <xs:element ref="ns1:EventDebounce"/>
                    <xs:element ref="ns1:ConfigSerialNumber"/>
                    <xs:element ref="ns1:MonitorWettingVoltage"/>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="_PdcStationName" type="xs:string"/>
    <xs:element name="_StationId" type="xs:integer"/>
    <xs:element name="_ServerPort" type="xs:integer"/>
    <xs:element name="_CommandServerPort" type="xs:integer"/>
    <xs:element name="_NetworkProtocol" type="xs:NCName"/>
    <xs:element name="_MaxWait" type="xs:integer"/>
    <xs:element name="_Verbose" type="xs:integer"/>
    <xs:element name="_DataRate" type="xs:integer"/>
    <xs:element name="_LineFreq" type="xs:integer"/>
    <xs:element name="_VerboseConcentrator" type="xs:integer"/>
    <xs:element name="UdpServers">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:_UdpServerPort"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="_UdpServerPort" type="xs:integer"/>
    <xs:element name="DfrId" type="xs:integer"/>
    <xs:element name="RecordingDeviceId" type="xs:NCName"/>
    <xs:element name="SampleRate" type="xs:integer"/>
    <xs:element name="LineFrequency" type="xs:integer"/>
    <xs:element name="ExportRate" type="xs:integer"/>
    <xs:element name="AnalogsCount" type="xs:integer"/>
    <xs:element name="DigitalsCount" type="xs:integer"/>
    <xs:element name="StationName" type="xs:string"/>
    <xs:element name="PrefaultTime" type="xs:integer"/>
    <xs:element name="PostfaultTime" type="xs:integer"/>
    <xs:element name="LtrPrefaultTime" type="xs:integer"/>
    <xs:element name="LtrPostfaultTime" type="xs:integer"/>
    <xs:element name="DatabaseConnectString" type="xs:string"/>
    <xs:element name="ChatterLimit" type="xs:integer"/>
    <xs:element name="ChatterRate" type="xs:decimal"/>
    <xs:element name="TriggerLimit" type="xs:integer"/>
    <xs:element name="CrossRecordServerPort" type="xs:integer"/>
    <xs:element name="DatabaseDataType" type="xs:NCName"/>
    <xs:element name="ExportAnalogBufferTime" type="xs:integer"/>
    <xs:element name="ExportAnalogSampleRate" type="xs:integer"/>
    <xs:element name="ExportBufferTime" type="xs:integer"/>
    <xs:element name="ContinuousOscillographyEnable" type="xs:integer"/>
    <xs:element name="AntiAliasFilterDelay" type="xs:decimal"/>
    <xs:element name="DisableAllDatabaseUse" type="xs:integer"/>
    <xs:element name="InitSound" type="xs:integer"/>
    <xs:element name="Ps" type="xs:NCName"/>
    <xs:element name="SignalTooLowFactor" type="xs:decimal"/>
    <xs:element name="EventDebounce" type="xs:decimal"/>
    <xs:element name="ConfigSerialNumber" type="xs:NCName"/>
    <xs:element name="MonitorWettingVoltage" type="xs:integer"/>
    <xs:element name="Pmus">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:Pmu"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pmu">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="ns1:_PmuName"/>
                <xs:element ref="ns1:_PmuId"/>
                <xs:element minOccurs="0" ref="ns1:_PmuServerIp"/>
                <xs:element ref="ns1:_PmuPort"/>
                <xs:element minOccurs="0" ref="ns1:_PmuUdpPort"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="ns1:_PmuEnable"/>
                    <xs:element ref="ns1:_PmuDataRate"/>
                    <xs:element ref="ns1:_PmuPhasorMode"/>
                    <xs:element ref="ns1:_PmuStreamType"/>
                    <xs:element ref="ns1:_UdpPort"/>
                </xs:choice>
                <xs:choice>
                    <xs:element ref="ns1:PmuInputs"/>
                    <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:PmuInput"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="name" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_PmuName" type="xs:NCName"/>
    <xs:element name="_PmuId" type="xs:integer"/>
    <xs:element name="_PmuServerIp" type="xs:NMTOKEN"/>
    <xs:element name="_PmuPort" type="xs:integer"/>
    <xs:element name="_PmuUdpPort" type="xs:integer"/>
    <xs:element name="_PmuDataRate" type="xs:integer"/>
    <xs:element name="_PmuPhasorMode" type="xs:NCName"/>
    <xs:element name="_PmuStreamType" type="xs:NCName"/>
    <xs:element name="_UdpPort" type="xs:integer"/>
    <xs:element name="PmuInputs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:PmuInput"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="HighLimit" type="xs:decimal"/>
    <xs:element name="LowLimit" type="xs:decimal"/>
    <xs:element name="_Channel" type="xs:integer"/>
    <xs:element name="_Phase" type="xs:string"/>
    <xs:element name="_InputType" type="xs:NCName"/>
    <xs:element name="_Input" type="xs:string"/>
    <xs:element name="_Id" type="xs:integer"/>
    <xs:element name="_LineGroupName" type="xs:string"/>
    <xs:element name="_AutoCalc" type="xs:NCName"/>
    <xs:element name="_PositiveResistance" type="xs:decimal"/>
    <xs:element name="_PositiveReactance" type="xs:decimal"/>
    <xs:element name="_ZeroResistance" type="xs:decimal"/>
    <xs:element name="_ZeroReactance" type="xs:decimal"/>
    <xs:element name="_LineMiles" type="xs:decimal"/>
    <xs:element name="_DecisionLogic" type="xs:string"/>
    <xs:element name="_Description" type="xs:NCName"/>
    <xs:element name="_HighLimit" type="xs:string"/>
    <xs:element name="_LowLimit" type="xs:string"/>
    <xs:element name="_Average" type="xs:integer"/>
    <xs:element name="_TriggerOutHold" type="xs:integer"/>
    <xs:element name="_Enable" type="xs:integer"/>
    <xs:element name="_Type" type="xs:NCName"/>
    <xs:element name="_ChatterLimit" type="xs:integer"/>
    <xs:element name="_ChatterRate" type="xs:decimal"/>
    <xs:element name="_TriggerLimit" type="xs:integer"/>
    <xs:element name="_Scale" type="xs:decimal"/>
    <xs:element name="_Dfr" type="xs:integer"/>
    <xs:element name="_PmuEnable" type="xs:integer"/>
    <xs:element name="PmuInput">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:_PmuInputName"/>
                <xs:element minOccurs="0" ref="ns1:_PmuInputType"/>
                <xs:element minOccurs="0" ref="ns1:_PmuEnable"/>
                <xs:choice>
                    <xs:element ref="ns1:_Input"/>
                    <xs:sequence>
                        <xs:element ref="ns1:_Dfr"/>
                        <xs:element ref="ns1:_Id"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="name"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="_PmuInputName" type="xs:NCName"/>
    <xs:element name="_PmuInputType" type="xs:NCName"/>
</xs:schema>
