CREATE database IF NOT EXISTS m9000;
DELETE FROM mysql.user where user='dfr';

FLUSH PRIVILEGES;
-- GRANT USAGE ON *.* TO 'dfr'@'localhost';
-- DROP USER 'dfr'@'localhost';
CREATE USER 'dfr'@'localhost' IDENTIFIED BY 'usi';
GRANT SELECT,INSERT,UPDATE,DELETE,ALTER, CREATE,DROP,TRIGGER, EXECUTE, EVENT,CREATE ROUTINE, ALTER ROUTINE,REFERENCES   ON m9000.* TO 'dfr'@'localhost';
GRANT USAGE,SELECT,INSERT,UPDATE,DELETE,ALTER, CREATE,DROP,TRIGGER ON m9000.* TO 'dfr'@'%';
FLUSH PRIVILEGES;
