#!/bin/bash

# confirmation
function ConfirmOrExit() {
while true
do
echo -n "Please confirm (y or n) :"
read CONFIRM
case $CONFIRM in
y|Y|YES|yes|Yes) break ;;
n|N|no|NO|No)
echo Aborting - you entered $CONFIRM
exit
;;
*) echo Please enter only y or n
esac
done
echo You entered $CONFIRM. Continuing ...
}

# remove old files for ser and alarms
function RemoveOldFiles() {
KEEP_ALIVE_DAYS="$1"
DEST_DIR="$2"
if [ -z "$KEEP_ALIVE_DAYS" -o "$KEEP_ALIVE_DAYS" -lt 1 ]
then
        KEEP_ALIVE_DAYS=1
fi
keepAliveDays=$(date +%s --date="-$(($KEEP_ALIVE_DAYS + 1)) days")
RESULT="$(date +%Y-%m-%d_%H:%M:%S)	Above to remove files older than $KEEP_ALIVE_DAYS day(s) from the dir $DEST_DIR. Removing below file(s) if any"
for file in "${DEST_DIR}"/*; do
    fdate=$(echo ${file##*/} | awk -F'_' ' { print $NF } '| awk -F'.' ' { print $1 } ')
        if ! [[ "$fdate" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]
        then
                continue;
        fi
    fsec=$(date +%s --date=${fdate})
    if [[ $fsec -lt $keepAliveDays ]]; then
	RESULT="$RESULT"$'\n'" \t\t\t\t${file##*/}"
        rm "${file}"
    fi
done
printf '%s\n' "$RESULT"
}

# Get the current time code
function timezone_code()
{
local TZ_OFFSET_CODE=$1
hr=$(echo $(( 10#${TZ_OFFSET_CODE:0:3} )))
min=$(echo $(( 10#${TZ_OFFSET_CODE:3:2} )))
if [ "$min" -ne 0 ]
then
        TZ_OFFSET_CODE="$hr$min"t
else
        TZ_OFFSET_CODE="$hr"t
fi
echo $TZ_OFFSET_CODE
}
