# M9K Backup Service

description	"M9k Backup Utility that exports Continuous COMTRADEs"

 start on (net-device-up
          and local-filesystems
	  and runlevel [2345]
	  and started mysql)
# start on filesystem and started networking
 stop on runlevel [016]

# We want it to automatically restart if it crashes
 respawn

script
echo "About to start M9K Station Service" > /var/log/m9k-backup.out
cd /home/dfr/m9k/M9kBackup/scripts >> /var/log/m9k-backup.out 2>&1
exec sudo -u dfr ./m9k-backup-launch.sh  >> /var/log/m9k-backup.out 2>&1
end script
